### ISSUE TITLE
HTML Comments?

### ISSUE THREAD

**Issue by PixlRainbow** [aMarCruz/rollup-plugin-jscc#6]
Is there a plan to support conditional compiling for HTML files as well? For example, so we can conditionally load either an unbundled script (e.g. during development, to test without need for repeated rollup runs) or a bundled script (processed with rollup).  
This could be potentially implemented using HTML comments like so:  
```html
<!-- #if _PRODUCTION
<script src="bundled.js"></script>
#else -->
<script src="main.js"></script>
<!-- #endif -->
```

**Comment by aMarCruz** [comment]
@PixlRainbow sorry, I hadn't seen your question.
Currently, this plugin does not have that functionality at compile time.
Closging this issue.
