### ISSUE TITLE
if entry point is named '.mjs' it does not works

### ISSUE THREAD

**Issue by muayyad-alsadi** [aMarCruz/rollup-plugin-jscc#8]
hi,

if I have `src/index.js` it works
if I renamed it to `src/index.mjs` it does not.

that is bad because rollup is about `.mjs` (EcmaScript modules).

**Comment by aMarCruz** [comment]
@muayyad-alsadi , you can use the `extensions` option:

```js
import { rollup } from 'rollup'
import jscc from 'rollup-plugin-jscc'

export default {
  input: 'src/main.js',
  plugins: [
    jscc({
      extensions: ['js', 'mjs', 'pug', 'html'],    // etc
      values: { _APPNAME: 'My App', _DEBUG: 1 },
    }),
  ],
  //...other options
}
```

I will include 'mjs' in the next version

**Comment by aMarCruz** [comment]
@muayyad-alsadi ,
rollup-plugin-jscc v2.0 is in npm, it includes "mjs" in the default extension list.
